// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgjanvoiaqmrpjpoqxyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnamFudm9pYXFtcnBqcG9xeHluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDI0MjEsImV4cCI6MjA2ODg3ODQyMX0.Vd973kzuZmmJdTra0NjeEf-4JdZjjQQfQzmKKqL0P7A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});